#!/usr/bin/env bash
# Runs inside the influxdb3 container on startup. Idempotent: safe to re-run.
# Creates the IIoT database, exposes the operator token (generated by the
# token-bootstrap service), creates last/distinct caches, and (in Task 17)
# registers the Processing Engine triggers.

set -euo pipefail

INFLUX_HOST="${INFLUX_HOST:-http://influxdb3:8181}"
INFLUX_DB="${INFLUX_DB:-iiot}"
TOKEN_FILE="/var/lib/influxdb3/.iiot-operator-token"

log() { echo "[init] $*"; }

wait_for_api() {
    local url="${INFLUX_HOST}/health"
    for _ in $(seq 1 120); do
        if curl -s --max-time 2 -o /dev/null "$url"; then return 0; fi
        sleep 1
    done
    echo "[init] FATAL: influxdb3 API did not become ready" >&2
    exit 1
}

read_token_json() {
    sed -n 's/.*"token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1" | head -n1
}

ensure_token() {
    if [[ ! -s "${TOKEN_FILE}" ]]; then
        echo "[init] FATAL: ${TOKEN_FILE} missing — token-bootstrap service failed" >&2
        exit 1
    fi
    local plain="/var/lib/influxdb3/.iiot-token-plain"
    if [[ ! -s "${plain}" ]]; then
        read_token_json "${TOKEN_FILE}" > "${plain}"
        chmod 600 "${plain}"
    fi
    log "admin token present (generated by token-bootstrap)"
}

cli() {
    local token
    token=$(read_token_json "${TOKEN_FILE}")
    influxdb3 "$@" --host "${INFLUX_HOST}" --token "${token}"
}

idempotent() {
    local label="$1"; shift
    local out
    if out=$(cli "$@" 2>&1); then
        log "created ${label}"
    elif echo "$out" | grep -qE "already exists|Conflict|409"; then
        log "${label} already exists"
    else
        echo "[init] FATAL while creating ${label}: $out" >&2
        exit 1
    fi
}

ensure_database() {
    idempotent "database ${INFLUX_DB}" create database "${INFLUX_DB}"
}

# Caches and several UI queries reference tables by name and require them
# to EXIST at query/create time. Seed each user table with one sentinel row
# at timestamp 1 ns (1970-01-01 — outside every recent-time window the UI
# queries) using tag sets the simulator/plugins never emit.
ensure_seed_tables() {
    local token
    token=$(read_token_json "${TOKEN_FILE}")
    local seeds=(
        'machine_state,site=__init,line_id=__init,station_id=__init,machine_id=__init state="__init",reason="__init" 1'
        'temperature,site=__init,line_id=__init,station_id=__init,machine_id=__init temp_c=0 1'
        'vibration,site=__init,line_id=__init,station_id=__init,machine_id=__init rms_mm_s=0 1'
        'part_events,site=__init,line_id=__init,station_id=__init,machine_id=__init,part_id=__init,quality=__init cycle_time_s=0 1'
        'alerts,source=__init,severity=__init,line_id=__init,machine_id=__init reason="__init",value=0 1'
        'shift_summary,line_id=__init,shift_id=__init oee=0,availability=0,performance=0,quality=0,units_total=0,units_good=0,downtime_top1_reason="__init",downtime_top2_reason="__init",downtime_top3_reason="__init",downtime_top1_seconds=0,downtime_top2_seconds=0,downtime_top3_seconds=0 1'
    )
    local body
    body=$(printf '%s\n' "${seeds[@]}")
    if curl -sf -X POST \
            "${INFLUX_HOST}/api/v3/write_lp?db=${INFLUX_DB}&precision=nanosecond" \
            -H "Authorization: Bearer ${token}" \
            -H "Content-Type: text/plain" \
            --data "${body}" >/dev/null 2>&1; then
        log "seeded all user tables"
    else
        log "sentinel writes may have failed (table-already-exists is fine); continuing"
    fi
}

ensure_caches() {
    idempotent "last_cache machine_state_last" create last_cache machine_state_last \
        --database "${INFLUX_DB}" --table machine_state
    idempotent "distinct_cache part_id_distinct" create distinct_cache part_id_distinct \
        --database "${INFLUX_DB}" --table part_events --columns part_id
}

ensure_triggers() {
    log "registering processing-engine triggers"

    # WAL trigger on machine_state — transition-detect downtime alerts
    idempotent "trigger downtime_detector" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "table:machine_state" \
        --path "wal_downtime_detector.py" \
        downtime_detector

    # WAL trigger on part_events — windowed scrap-rate quality alerts
    idempotent "trigger quality_excursion" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "table:part_events" \
        --path "wal_quality_excursion.py" \
        --trigger-arguments "window=20,scrap_threshold=0.10" \
        quality_excursion

    # Schedule trigger: shift boundaries 06:00, 14:00, 22:00 UTC.
    # 6-field cron: <sec> <min> <hour> <dom> <mon> <dow>
    idempotent "trigger shift_summary" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "cron:0 0 6,14,22 * * *" \
        --path "schedule_shift_summary.py" \
        --trigger-arguments "ideal_cycle_s=30.0" \
        shift_summary

    # Request trigger: HTTP path /api/v3/engine/andon_board
    idempotent "trigger andon_board" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "request:andon_board" \
        --path "request_andon_board.py" \
        andon_board

    # Enable all triggers (idempotent — enabling an already-enabled trigger is a no-op).
    for t in downtime_detector quality_excursion shift_summary andon_board; do
        cli enable trigger "${t}" --database "${INFLUX_DB}" 2>/dev/null || \
            log "trigger ${t} enable no-op"
    done
}

main() {
    wait_for_api
    ensure_token
    ensure_database
    ensure_seed_tables
    ensure_caches
    ensure_triggers
    log "initialization complete"
}

main "$@"
