#!/usr/bin/env bash
# Runs inside the influxdb3 container on startup. Idempotent: safe to re-run.
# Creates the IIoT database, exposes the operator token (generated by the
# token-bootstrap service), creates last/distinct caches, and (in Task 17)
# registers the Processing Engine triggers.

set -euo pipefail

INFLUX_HOST="${INFLUX_HOST:-http://influxdb3:8181}"
INFLUX_DB="${INFLUX_DB:-iiot}"
TOKEN_FILE="/var/lib/influxdb3/.iiot-operator-token"

log() { echo "[init] $*"; }

wait_for_api() {
    local url="${INFLUX_HOST}/health"
    for _ in $(seq 1 120); do
        if curl -s --max-time 2 -o /dev/null "$url"; then return 0; fi
        sleep 1
    done
    echo "[init] FATAL: influxdb3 API did not become ready" >&2
    exit 1
}

read_token_json() {
    sed -n 's/.*"token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1" | head -n1
}

ensure_token() {
    if [[ ! -s "${TOKEN_FILE}" ]]; then
        echo "[init] FATAL: ${TOKEN_FILE} missing — token-bootstrap service failed" >&2
        exit 1
    fi
    local plain="/var/lib/influxdb3/.iiot-token-plain"
    if [[ ! -s "${plain}" ]]; then
        read_token_json "${TOKEN_FILE}" > "${plain}"
        chmod 600 "${plain}"
    fi
    log "admin token present (generated by token-bootstrap)"
}

cli() {
    local token
    token=$(read_token_json "${TOKEN_FILE}")
    influxdb3 "$@" --host "${INFLUX_HOST}" --token "${token}"
}

idempotent() {
    local label="$1"; shift
    local out
    if out=$(cli "$@" 2>&1); then
        log "created ${label}"
    elif echo "$out" | grep -qE "already exists|Conflict|409"; then
        log "${label} already exists"
    else
        echo "[init] FATAL while creating ${label}: $out" >&2
        exit 1
    fi
}

ensure_database() {
    idempotent "database ${INFLUX_DB}" create database "${INFLUX_DB}"
}

# Caches and several UI queries reference tables by name and require them
# to EXIST at cache-create / query-plan time. Create each user table
# explicitly via POST /api/v3/configure/table so the schema is registered
# before the simulator (and plugins that read those tables) start. The
# alternative — implicit table creation by first write — leaves a race
# window where the LVC/DVC `create` calls and UI queries can fail with
# "table not found".
create_table() {
    local table="$1"
    local body="$2"
    local token
    token=$(read_token_json "${TOKEN_FILE}")
    local out code
    out=$(mktemp)
    code=$(curl -s -o "${out}" -w "%{http_code}" -X POST \
        "${INFLUX_HOST}/api/v3/configure/table" \
        -H "Authorization: Bearer ${token}" \
        -H "Content-Type: application/json" \
        --data "${body}")
    case "${code}" in
        200|201|204) log "created table ${table}" ;;
        409)         log "table ${table} already exists" ;;
        *)
            echo "[init] FATAL while creating table ${table} (HTTP ${code}): $(cat "${out}")" >&2
            rm -f "${out}"
            exit 1
            ;;
    esac
    rm -f "${out}"
}

ensure_user_tables() {
    create_table machine_state '{
        "db": "'"${INFLUX_DB}"'",
        "table": "machine_state",
        "tags": ["site", "line_id", "station_id", "machine_id"],
        "fields": [
            {"name": "state",  "type": "utf8"},
            {"name": "reason", "type": "utf8"}
        ]
    }'
    create_table temperature '{
        "db": "'"${INFLUX_DB}"'",
        "table": "temperature",
        "tags": ["site", "line_id", "station_id", "machine_id"],
        "fields": [
            {"name": "temp_c", "type": "float64"}
        ]
    }'
    create_table vibration '{
        "db": "'"${INFLUX_DB}"'",
        "table": "vibration",
        "tags": ["site", "line_id", "station_id", "machine_id"],
        "fields": [
            {"name": "rms_mm_s", "type": "float64"}
        ]
    }'
    create_table part_events '{
        "db": "'"${INFLUX_DB}"'",
        "table": "part_events",
        "tags": ["site", "line_id", "station_id", "machine_id", "part_id", "quality"],
        "fields": [
            {"name": "cycle_time_s", "type": "float64"}
        ]
    }'
    create_table alerts '{
        "db": "'"${INFLUX_DB}"'",
        "table": "alerts",
        "tags": ["source", "severity", "line_id", "machine_id"],
        "fields": [
            {"name": "reason", "type": "utf8"},
            {"name": "value",  "type": "float64"}
        ]
    }'
    create_table shift_summary '{
        "db": "'"${INFLUX_DB}"'",
        "table": "shift_summary",
        "tags": ["line_id", "shift_id"],
        "fields": [
            {"name": "oee",                   "type": "float64"},
            {"name": "availability",          "type": "float64"},
            {"name": "performance",           "type": "float64"},
            {"name": "quality",               "type": "float64"},
            {"name": "units_total",           "type": "float64"},
            {"name": "units_good",            "type": "float64"},
            {"name": "downtime_top1_reason",  "type": "utf8"},
            {"name": "downtime_top2_reason",  "type": "utf8"},
            {"name": "downtime_top3_reason",  "type": "utf8"},
            {"name": "downtime_top1_seconds", "type": "float64"},
            {"name": "downtime_top2_seconds", "type": "float64"},
            {"name": "downtime_top3_seconds", "type": "float64"}
        ]
    }'
}

ensure_caches() {
    idempotent "last_cache machine_state_last" create last_cache machine_state_last \
        --database "${INFLUX_DB}" --table machine_state
    idempotent "distinct_cache part_id_distinct" create distinct_cache part_id_distinct \
        --database "${INFLUX_DB}" --table part_events --columns part_id
}

ensure_triggers() {
    log "registering processing-engine triggers"

    # WAL trigger on machine_state — transition-detect downtime alerts
    idempotent "trigger downtime_detector" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "table:machine_state" \
        --path "wal_downtime_detector.py" \
        downtime_detector

    # WAL trigger on part_events — windowed scrap-rate quality alerts
    idempotent "trigger quality_excursion" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "table:part_events" \
        --path "wal_quality_excursion.py" \
        --trigger-arguments "window=20,scrap_threshold=0.10" \
        quality_excursion

    # Schedule trigger: shift boundaries 06:00, 14:00, 22:00 UTC.
    # 6-field cron: <sec> <min> <hour> <dom> <mon> <dow>
    idempotent "trigger shift_summary" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "cron:0 0 6,14,22 * * *" \
        --path "schedule_shift_summary.py" \
        --trigger-arguments "ideal_cycle_s=30.0" \
        shift_summary

    # Request trigger: HTTP path /api/v3/engine/andon_board
    idempotent "trigger andon_board" create trigger \
        --database "${INFLUX_DB}" \
        --trigger-spec "request:andon_board" \
        --path "request_andon_board.py" \
        andon_board

    # Enable all triggers (idempotent — enabling an already-enabled trigger is a no-op).
    for t in downtime_detector quality_excursion shift_summary andon_board; do
        cli enable trigger "${t}" --database "${INFLUX_DB}" 2>/dev/null || \
            log "trigger ${t} enable no-op"
    done
}

main() {
    wait_for_api
    ensure_token
    ensure_database
    ensure_user_tables
    ensure_caches
    ensure_triggers
    log "initialization complete"
}

main "$@"
